//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hazmat_book
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Deposits = new HashSet<Deposit>();
        }
    
        public int Book_Id { get; set; }
        public string Name { get; set; }
        public string Publisher { get; set; }
        public string Page { get; set; }
        public string Language { get; set; }
        public string Description { get; set; }
        public string Barcode { get; set; }
        public string Since { get; set; }
        public string Writer { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public string Updated_At { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deposit> Deposits { get; set; }
    }
}
