//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hazmat_book
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int Deposit_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Book_Id { get; set; }
        public string Deposit_Given_Date { get; set; }
        public string Deposit_Taken_Date { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public string Updated_At { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
